package nl.edsoft.klaverjas

/**
 * Wat de computer doet bij tactieknummer `nr`, kort genoeg voor één regel. De nummers
 * komen uit de broncode van 1994 en zijn in alle versies dezelfde. 44 en 61 zijn nooit
 * toegekend; 70 is van de zoekende speler en heeft [Taal.statTactiekZoeken].
 */
fun Taal.tactiekNaam(nr: Int): String = when (nr) {
        0 -> t("geen tactiek", "no tactic")
        7 -> t("Zekere slag met de meeste roemkans", "Sure trick with the best meld chance")
        1 -> t("Zekere tafelkaart, hij heeft een kale tien", "Sure table card, bare ten opposite")
        2 -> t("Zekere handkaart, hij heeft een kale tien", "Sure hand card, bare ten opposite")
        50 -> t("Mijn aas tegen zijn kale tien", "My ace against his bare ten")
        41 -> t("Kleur aanspelen om troef kwijt te raken", "Lead a suit to shed a trump")
        10 -> t("Bijna zekere slag van tafel, met roem", "Near-certain trick from table, with meld")
        62 -> t("Bijna zekere slag uit de hand, met roem", "Near-certain trick from hand, with meld")
        9 -> t("Zekere slag van tafel, geen troef", "Sure trick from table, no trump")
        8 -> t("Zekere slag uit de hand, geen troef", "Sure trick from hand, no trump")
        57 -> t("Zekere slag van tafel, troef trekken", "Sure trick from table, drawing trumps")
        58 -> t("Zekere slag uit de hand, troef trekken", "Sure trick from hand, drawing trumps")
        47 -> t("Kleur aanspelen die ik zelf niet heb", "Lead a suit I don't hold myself")
        11 -> t("Beste slagkans van tafel", "Best trick chance from the table")
        63 -> t("Beste slagkans uit de hand", "Best trick chance from the hand")
        5 -> t("Troef trekken met een lage kaart", "Draw trumps with a low card")
        55 -> t("Overige zekere slag van tafel", "Other sure trick from the table")
        56 -> t("Overige zekere slag uit de hand", "Other sure trick from the hand")
        54 -> t("Troef van tafel gebruiken", "Use the trump on the table")
        13 -> t("Lage kaart zonder roemkans", "Low card without meld chance")
        14 -> t("Lage kaart, geen troef", "Low card, no trump")
        15 -> t("De laagste kaart die er nog is", "The lowest card left")
        40 -> t("Enige kaart van die kleur op tafel", "Only table card of the suit led")
        18 -> t("De enige hogere troef", "The only higher trump")
        19 -> t("Hogere troef met de beste kans", "Higher trump with the best chance")
        42 -> t("Van de hogere kaarten de minste roem", "Least meld among the higher cards")
        6 -> t("De achtergehouden kaart alsnog spelen", "Play the card held back earlier")
        45 -> t("De troef die weg moest", "The trump that had to go")
        12 -> t("Troef van tafel kwijtraken", "Get rid of the table trump")
        36 -> t("Enige kaart van die kleur", "Only card of that suit")
        66 -> t("De enige hogere troef", "The only higher trump")
        67 -> t("Hogere troef met een goede kans", "Higher trump with a good chance")
        37 -> t("Hogere troef met de meeste roem", "Higher trump with the most meld")
        38 -> t("Enige kaart van die kleur", "Only card of that suit")
        17 -> t("Kan niet hoger: roem meepakken", "Cannot go higher: take the meld")
        20 -> t("Hogere troef met de meeste roem", "Higher trump with the most meld")
        39 -> t("Kan niet hoger: minste roem weggeven", "Cannot go higher: give away least meld")
        30 -> t("Enige hogere troef, of troef van tafel", "Only higher trump, or a table trump")
        16 -> t("Beste tafelkaart van de gevraagde kleur", "Best table card of the suit led")
        21 -> t("Tafelkaart die de uitkomst verslaat", "Table card that beats the lead")
        22 -> t("Partner heeft de slag: roem meepakken", "Partner has the trick: take the meld")
        49 -> t("Handkaart die de uitkomst verslaat", "Hand card that beats the lead")
        4 -> t("Slag is binnen: roem meepakken", "Trick is ours: take the meld")
        23 -> t("Minste roem weggeven, niet de tien", "Least meld away, but not the ten")
        24 -> t("Handkaart met de meeste roem", "Hand card with the most meld")
        48 -> t("Meeste roem zonder de slag over te nemen", "Most meld without taking the trick")
        46 -> t("Hogere kaart van die kleur", "Higher card of that suit")
        3 -> t("De minste roem weggeven", "Give away the least meld")
        26 -> t("Laagste troef van tafel erbij", "Add the lowest trump from the table")
        27 -> t("Laagste troef uit de hand erbij", "Add the lowest trump from the hand")
        28 -> t("Overtroeven met troef van tafel", "Overtrump with a table trump")
        29 -> t("Overtroeven met troef uit de hand", "Overtrump with a hand trump")
        31 -> t("Troef uit de hand met de beste kans", "Hand trump with the best chance")
        59 -> t("Keuze teruggedraaid: er is ingetroefd", "Choice withdrawn: someone trumped in")
        43 -> t("Slag is binnen: de hoogste roem", "Trick is ours: the highest meld")
        32 -> t("De kaart met de minste roem", "The card with the least meld")
        51 -> t("Kale tien afgooien nu het kan", "Discard the bare ten while it is safe")
        68 -> t("Duurste rommel uit de hand", "Priciest junk from the hand")
        52 -> t("Kale tien van tafel afgooien", "Discard the bare ten from the table")
        69 -> t("Duurste rommel van tafel", "Priciest junk from the table")
        60 -> t("Introeven uit de hand, om de roem", "Trump in from hand, for the meld")
        25 -> t("Introeven van tafel, om de roem", "Trump in from table, for the meld")
        34 -> t("Van die kleur de minste roem", "Least meld of that suit")
        33 -> t("Goedkoopste kaart van die kleur", "Cheapest card of that suit")
        64 -> t("Hogere troef bijgooien", "Add a higher trump")
        65 -> t("Laagste troef bijgooien", "Add the lowest trump")
        53 -> t("Goedkoopste kaart, geen troef", "Cheapest card, no trump")
        35 -> t("Gooi maar wat: de goedkoopste", "Anything goes: the cheapest")
    else -> if (engels) "unknown" else "onbekend"
}
