// Automatisch gegenereerd uit Klaverjas/KJKRT.C door genkaarten.py -
// niet met de hand aanpassen.
// Bron: de tekenroutines aas(), heer(), vrouw(), boer() en kleuren().
// Elk teken is een pixel; de kleurtabel per plaatkaart komt uit de switch
// in de bijbehorende C-functie. Kleur -1 betekent "GREEN + kleurnummer",
// waardoor die pixels per kaartkleur verschillen, precies als in het origineel.

enum KaartData {
    static let aas: [String] = [
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccaaaaaaacccccccccccccccccccccc",
        "cccccccccccccccccccccaaaaaaaaaaccccccccccccccccccc",
        "ccccccccccccccccccccaaaaaaaaaaaaaccccccccccccccccc",
        "cccccccccccccccccccaaaaaaaaaaacccccccccccccccccccc",
        "cccccccccccccccccccyyyyyyyyyyycccccccccccccccccccc",
        "cccccccaaaaacccccccyyyyyyyyyyccccaaaaaaccccccccccc",
        "ccccccaaaaaaaccccccccccccccccccaaaaaaaaaaaaacccccc",
        "ccccccaaaaaaaaccccccccccRccccccaaaaaaaaaaaaccccccc",
        "cccccyyyyyyyyyccccccccccRRcccccyyyyyyyyyaccccccccc",
        "ccccccyyyyyyyccccccccccRrRcccccyyyyyyyyccccccccccc",
        "ccccccyyyyyycccccccccccRrRcccccyyyyyyycccccccccccc",
        "cccccccccccccccccccccccRrrRccccccccccccccccccccccc",
        "ccccccccccccccccccccccRrrrRccccccccccccccccccccccc",
        "ccccccccccccccccccccccRrrrRccccccccccccccccccccccc",
        "ccccccRccccccccccccccRrrrrrRcccccccccccccccccccccc",
        "ccccccRRcRccccccccccRrruuurrRccccccccccccccccccccc",
        "cccccRrrzrRccccccccczYYyyyYYzccccccccccccccccccccc",
        "ccccRrrrzrRccccccccczyzuuuzuzccccccRcccccccccccccc",
        "cccczzzzzzzRRRRRcccczuuuuuuuzcccccRzRcccRccccccccc",
        "cccczeuuzuzrrrzRRRRRzeuzzzuuzccccRrzrRcRRccccccccc",
        "cccczeuuzezrrrrzrrrrzzzeuuzzzcccRrrzrRRrrRcccccccc",
        "cccczeuuzuzrrrrzrrrrzeeeuuuuzccRrrzzzRRrrrRccccccc",
        "cccczeeuzezrrrrrzrrrzeeeuuuuzcczzzuuzzzzzrRccccccc",
        "cccczeuuzuzrrrrrzrrrzeeeuuuuzcczeeuuzuzeezzccccccc",
        "cccczeuuzuzrrrrrrzrrzeeuuuuuzzczeeuuzuzuuuzccccccc",
        "cccczezzzzzzzzzzzzzzzeeuuuuuzuzzeeuuzuzuuuzccccccc",
        "cggczuzuzuzuzuzuzuzuzeuuuuuuzuuuzeuuzuzuuuzccccccc",
        "ggggzuzeuuuuuzzzzzzzzeuuuuuuzuuuzuuuzuzuuuzccccccc",
        "ggggzuzzzzzzzzuuuuuuzeuuuuuuzuuuzuuuzuzuuuzccccccc",
        "ggggzuzeeuguuguuuuuuzeuuuuuuzuuuzuuuzuzuuuziiiiiii",
        "gzgizuzeeuguuguuuuuuzuuuuuuuzuuuzuuuzuzuuuziiiiiii",
        "iziizuzeuugzggguuuuuzeeuuuuuzuuuzuuuzuzuuuzzzzzzzz",
        "iziizuzeuuuzuuuuuuuuzeuuuuuuzuuuzuuuzuzuubbuuuubbz",
        "iziizuzeguuzuuguuuugzeeuuuuuzuuuzUUUzbzUUbbuuuubbz",
        "iziizuzeguuzuggguuggzuuuuuuuzuuggbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbggggggggzuuuuuuuzggbbbbbbbbbbbbbbbbbbb",
        "wwwwwwwbbbbbbbbbbbbbzUUUUUUUzbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbwwwwwgbbbbbbbbbbbbwwwggbbbbbbbbbbbbbbb",
        "bbbbbbggwbbbbbbbbbbwwwwwwggbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbggbbbbbbbbbbbbbbbbbggbbbwwwwwwggbbbbbbbbbbbb",
        "bbbbbbbbbbbbbggbwwwwwwwbbbbbbbbbbbbbggbbbbbbbbbbbb",
        "bbbbbbbbbbbbbggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbgbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbgiiiiiiiiiiiiiiiibbbbbbbbbiiii",
        "bbbbiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    ]

    static let aasPalet: [(teken: Character, kleur: Int)] = [
        ("a", 7),
        ("b", 1),
        ("c", 9),
        ("e", 14),
        ("g", 2),
        ("i", 10),
        ("j", 12),
        ("n", 11),
        ("o", 3),
        ("p", 5),
        ("r", -1),
        ("t", 13),
        ("u", 6),
        ("w", 15),
        ("y", 8),
        ("z", 0),
    ]

    static let heer: [String] = [
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEeJjEeJjEeJjxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEeJjEeJjEeJjxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEeJjEeJjEeJjxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxzzzzzzzzzzzzxxxxxxxxxxjxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEegeegeegeeExxxxxxxxxjjjjxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEEEEEEEEEEEExxxxxxxxjjjjjjxxxxxx",
        "xxxxxxxxxxxxxxxxxxrrrwwwwwwwwwxxxxxxxxxjjjjxxxxxxx",
        "xxxxxxxxxxxxxxxxxxrrrwwwwwwwwwrxxxxxxxxxjjxxxxxxxx",
        "xxxxxxxxxxxxxxxxxrrrrrwzzwwzzrrxxxxxxxxEEEExxxxxxx",
        "xxxxxxxxxxxxxxxxrrrrrwwwwzwwwrrxxxxxxxEeeExxxxxxxx",
        "xxxxxxxxxxxxxxxxrrrrwwwwwwzwwrrxxxxxxxEbeExxxxxxxx",
        "xxxxxxxxxxxxxxxrrrrrwwwwwwzwwrrxxxxxxEeeExxxxxxxxx",
        "xxxxxxxxxxxxxxxrrrrrwwwwwzzwwrrxxxxxxEjjExxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrwwwwwwwwwrrxxxxxEjjExxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrzrrrzrrrxxxxxEeeExxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrrrzzrrrrxxxxxEeeExxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrrrrrrrwrxxxxEegExxxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrrrrrrrwrxxxxEeeExxxxxxxxxxx",
        "xxxxxxxxxxxxxxrErrPrrrrrrrrrrPrxxxxEbeExxxxxxxxxxx",
        "xxxxxxxxxxxxxxEeePppppprrrrrrpppPxEeeExxxxxxxxxxxx",
        "xxxxxxxxxxxxxEeeePppppppprrrpppPeEppExxxxxxxxxxxxx",
        "xxxxxxxxxxxBbEeeeePpppppppppppPeeEppExxxxxxxxxxxxx",
        "xxxxxxxxxxBbbbbEeeeePPPPppppEEeeEeeExxxxxxxxxxxxxx",
        "xxxxxxxxxBbbbbbEEeeeeeeeEEEEeeeeEeeExxxxxxxxxxxxxx",
        "xxxxxxxxBbbbbbbbbEeeeeeeeeeeeeeeEeeExxxxxxxxxxxxxx",
        "xxxxxxxxBbbbbbbbbbEEeeeeeeeeeeeEeeEBxxxxxxxxxxxxxx",
        "xxxxxxxxBbbbbbbbbbbbbEEEEEEEEbEeeEbbBxxxxxxxxxxxxx",
        "xxxxxxxBbbbbbbbbbbbbbbbbbbbbbbEeeEbbbbBxxxxxxxxxxx",
        "xxxxxxxBbbbbbbbbbbbbbbbbGbbbbbErrEbbbbbBxxxxxxxxxx",
        "xxxxxxxBbbbbbbbbbbbbbbbGgGGbbErrEbbbbbbBxxxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbbbGggggGbEeeEbbbbbbbBxxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbbbGgggggEttEbbbbbbbbBxxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbbGgpppggEetEbbbbbbbbbBxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbGzzpppzEeeEbbbbbbbbbbBxxxxxxxx",
        "xxxxxBbbbbbbbbbbbbbbGggpppgEeeEgBbbbbbbbbbBxxxxxxx",
        "xxxxxBbbbbbbbbbbbbbGgggggggEezEgBbbbbbbbbbBxxxxxxx",
        "xxxxxBbbbbbbbbbbbbbGggggggEieEgggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbbbGggggggEiiEgggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbbGggggggEeeEggggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbbGggggggEooEggggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbGgggggggEooEgggggBbbbbbbbbbBxxxxx",
        "xxxxxBbbbbbbbbbbbGggggggEeeEggggggBbbbbbbbbbBxxxxx",
        "xxxxxBbbbbbbbbbbGgtttgggEeeEggggttBbbbbbbbbbBxxxxx",
        "xxxxBbbbbbbbbbbGgttgttgEeuEggggttgtBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbbGgttgggttEuuEgggttgggBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbbGttgggggEeeEgggttggggBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbGttggggggEeeEggttgggggBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbGtgggggggEeetgttggggggBbbbbbbbbbBxxxx",
    ]

    static let heerPalet: [(teken: Character, kleur: Int)] = [
        ("a", 7),
        ("b", 1),
        ("c", 9),
        ("e", 14),
        ("g", 2),
        ("i", 10),
        ("j", 12),
        ("o", 3),
        ("p", 5),
        ("r", -1),
        ("t", 11),
        ("u", 6),
        ("w", 15),
        ("x", 13),
        ("y", 8),
        ("z", 0),
    ]

    static let vrouw: [String] = [
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaiijjiijjiijaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaiijjiijjiijaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaEEEEEEEEEEEaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaEeeettteeeEaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaEeettttteeEaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaazzzzzzzzzzzaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaRrrrrrrrrrrrRaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrzrrrrrrrrrrRaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrzrrrrrrrrrrrRaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrzwwwwwwwwrrrPPPaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrwwwwwwwwwrrrPppPaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaRrwwwwwzzwwwrPppppPaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaZwzzwwzzwwwrrPppPcaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaZwzzwzwwwwwwrPPPccaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaZwwwzwwwwwwwZcccccaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaZwwwzzwwwwwwZcccccaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaZwwwwwzwwwZccccccaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaZwzzzwwwzZcccccccaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwzwZcccccccaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZzzzzwwwwZcccccccaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwwwwZcccccccaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwwwwwZccccccaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwwwwwZcccccccaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaBZZZwwwwwwwwwwZccccccaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaBbBwwwwwwwwwwwBbBccccccaaaaaaaaaa",
        "aaaaaaaaaaaIZZZZZZBbbbBwwwwwwBbbbbEEccccaaaaaaaaaa",
        "aaaaaaaaaIiiiIaWWWwwBbbBBBBBBbbbbEeeeEccaaaaaaaaaa",
        "aaaaaaaaIIiiIwwwwwwwBbbbbbbbbbbbEeeeeeEcaaaaaaaaaa",
        "aaaaaaaaIiiiiIwwwwwwwwwBBBBBwwwEeeeeeeEaaaaaaaaaaa",
        "aaaaaaaaIiiiiiIwwwwwwwwwwwwwwwEEeeeeeeeEaaaaaaaaaa",
        "aaaaaaaIiiiiiiIwwwwwwzwwwwwwwwEeeeeeeeeEEaaaaaaaaa",
        "aaaaaaaIiiiiiiiIwwwwzwwwwwwwIEeeeeeeeeeeEaaaaaaaaa",
        "aaaaaaIiiiiiiiiIwwwzwwwwwwIiEeeeeeeeeeeeIaaaaaaaaa",
        "aaaaaaIiiiiiiiiiIwwzwwwwIiiEeeeeeeeeeeIiIaaaaaaaaa",
        "aaaaaaIiiiiiiiiiIwzwwwIiiiiEeeeeeeeeIiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiIzwIiiiiiiEeeeeeeeIiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiIIiiiiiiEeeeeeeeIiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiiieeeeeeeeIiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiiEeeeeeeeeIiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiIaaaaaaaaa",
        "aaaaUuiiiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiiUaaaaaaaaa",
        "aaaaUuuiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiUuUaaaaaaaaa",
        "aaaaUuuuiiiiiiiiiiiiiEeeeeeeeEiiiijjjUuuUaaaaaaaaa",
        "aaaaUuuujjjjjjjiiiiiiEeeeeeeeEjjjjjjjUuuUaaaaaaaaa",
        "aaaaUuuujjjjjjjjjjjjEeeeeeeeEjjjjjjjUuuuUaaaaaaaaa",
        "aaaaUuuujjjjjjjjjjjjEeeeeeeeEjjjjjiUuuuuUaaaaaaaaa",
        "aaaUuuuuiiiiijjjjjjEeeeeeeeEiiiiiiUuuuuuUaaaaaaaaa",
    ]

    static let vrouwPalet: [(teken: Character, kleur: Int)] = [
        ("a", 7),
        ("b", 1),
        ("c", 9),
        ("e", 14),
        ("g", 2),
        ("i", 10),
        ("j", 12),
        ("o", 3),
        ("p", 5),
        ("r", -1),
        ("t", 11),
        ("u", 6),
        ("w", 15),
        ("x", 13),
        ("y", 8),
        ("z", 0),
    ]

    static let boer: [String] = [
        "ccccccccccccccccccccccccccccJJJJJccccccccccccccccc",
        "ccccccccccccccccccccccccccJJjjjjJccccccccccccccccc",
        "cccccccccccccccccccccccccJjjjjjJcccccccccccccccccc",
        "ccccccccccccccccccccccccJjjjjjJccccccccccccccccccc",
        "cccccccccccccccccccccccJjjjjjJcccccccccccccccccccc",
        "cccccwwwwwwwwwwwwwccccJjjjjJJccccccccccccccccccccc",
        "ccccwwwwwwwwwwwwwwwwpJjjjJJcccccccccwwwwwccccccccc",
        "ccccccwwwwwwwwwwwwpPJjjJJPPccccccccwwwwwwwcccccccc",
        "ccccwwwwwwwwwwwwwwwPJjJppppPPccccccccccccccccccccc",
        "ccwwwwwwwwwwwwwwcccPJJpppppppPPPcccccccccccccccccc",
        "cwwwwwwwwwwwwwcccPPpppppppppppppPPPcccccgggggggccc",
        "cwwwwwwwwwwwwwcccPppppppppppppppppPccgggggggjjgggc",
        "cyyyyyyyyyyyyyccccPPPPPPPPPPpppppPPccgggjjggjjggjj",
        "cyyyyyyyyyyyyycccccRrrrWwwwPPPPPPcccggggjjggggggjj",
        "cccccccYcccccccccccRrrWwwwwwwwrrRcccggggggjjggjjgg",
        "cccccccYYcccccccccRrrWwZZwwZZwWrRccggjjgggjjggjjgg",
        "cccccccYyYccccccccRrWwwwwZwwwwWrRcccgjjggjjggggggg",
        "cccccccYyyYYccccccRrWwwwwZwwwwWrRcccgggggjjggggjjg",
        "cccccccYyyYyYcccccRrWwwwwZwwwwWrRcccccgggggjjggjjg",
        "ccccccccYyYYyYccccRrrWwWrrrrwwWrRcccccccgggjjggggg",
        "ccccccccYyYUYyYcccRrrrWWrrrrwwWrRccccccccccuuuuccc",
        "ccccccccYyYUUYyYccRRRRwwZZZZWWRRRccccccccccuuuuccc",
        "ccccccccYyYUuUYyYccccccZrrrrwzwRcccccccccccuuuuccc",
        "ccccccccYyYcUuUYYYccccZWrrrrzwwZcccccccccccuuuuccc",
        "cccccccccYYcUuUccYYcccZwrrrrwwwwZccccccccccuuuuccc",
        "cccccccccYcccUuUcccYcZWwwwwwwwwwZccccccccccuuuuccc",
        "cccccccccYcccUuUcccccZWWWWWWWWWWWZEEEccccccuuuuccc",
        "ccccccccccccccUuUccjjjjwwwjeeeeeeeeeeEcccccuuuuccc",
        "cccccccccccccccUuUjjjjjjjjEeeeeeeeeeeeEccccuuuuccc",
        "ccccccccccGGGGGUuUbbbjjjjEeeeeeeeeeeeeeEcccuuuuccc",
        "ccccccccGGggggggUuUbbbbbbEeeeeeeeeeeeeeEcccuuuuccc",
        "cccccccGgggggggugUuUbbbbEeeeeeeeeeeeeeeEEccuuuuccc",
        "cccccccGgggggggggUuUbbbEeeeeeeeeeeeeEEEggGcuuuuccc",
        "ccccccGggggggggBbBUuUbEeeeeeeeeeeeeEgggggGcuuuuccc",
        "ccccccGgggggggBbbbUuUeEeeeeeeeeeeEgggggggGcuuuuccc",
        "cccccGgggggggBbbbbbUuUeeeeeeeeeeEgggggggggGuuuuccc",
        "cccccGgggggggBbbbbgUuUeeeeeeeeeEggggggggggGuuuuccc",
        "cccccGgggggggBbbbbbbUuUeeeeeeeeEgggggggggggGuuuccc",
        "cccccGgggggggBbbbbbbUuUeeeeeeeEbbbGgggggggggGuuccc",
        "iiiiiGgggggggBbbbbbEeUuUeeeeeEbbbbBGgggggggggGuiii",
        "iiiiiGgggggggBbbbbEeeUuUeeeeeEbbbbBGggggggggggGiii",
        "iiiiiGgggggggBbbbEeeeeUuUeeeeEbbbbBiGgggggggggGiii",
        "iiiiGgggggggBbbbbEeeeeUuUeeeEbbbbbBiiGggggggggGiii",
        "iiiiGgggggggBbbbEeeeeeeUuUeeEbbbbBiiiGgggggggGiiii",
        "iiiiGgggggggBbbbEeeeeeeUuUeebbbbbBiiGggggggggGiiii",
        "iiiiGgggggggBbbEeeeeeeeeUuUeebbbbBiiGgggggggGiiiii",
        "iiiiGgggggggBbbEeeeeeeeeeUuUebbbbBiiGggggggGiiiiii",
        "iiiiGgggggggBbbEeeeeeeeeEUuUebbbbBiGggggggGiiiiiii",
        "iiiiGgggggggBBeeeeeeeeeeEbUuUbbbbBGgggggggGiiiiiii",
    ]

    static let boerPalet: [(teken: Character, kleur: Int)] = [
        ("a", 7),
        ("b", 1),
        ("c", 9),
        ("e", 14),
        ("g", 2),
        ("i", 10),
        ("j", 12),
        ("o", 3),
        ("p", 5),
        ("r", -1),
        ("t", 11),
        ("u", 6),
        ("w", 15),
        ("x", 13),
        ("y", 8),
        ("z", 0),
    ]

    static let klaver: [String] = [
        "wwwwwzzzwwwwww",
        "wwwwzzzzzwwwww",
        "wwwwzzzzzwwwww",
        "wwwwwzzzwwwwww",
        "wzzwwwzwwwzzww",
        "zzzzzwzwzzzzzw",
        "zzzzzzzzzzzzzw",
        "zzzzzwzwzzzzzw",
        "wzzwwwzwwwzzww",
        "wwwwwwzwwwwwww",
        "wwwwwzzzwwwwww",
        "wwwwwzzzwwwwww",
        "wwwwzzzzzwwwww",
        "wwwwwwwwwwwwww",
    ]

    static let schoppen: [String] = [
        "wwwwwwZwwwwwww",
        "wwwwwZZZwwwwww",
        "wwwwZZZZZwwwww",
        "wwZZZZZZZZZwww",
        "wZZZZZZZZZZZww",
        "ZZZZZZZZZZZZZw",
        "ZZZZZZZZZZZZZw",
        "ZZZZZZZZZZZZZw",
        "wZZZZwZwZZZZww",
        "wwZZwZZZwZZwww",
        "wwwwwwZwwwwwww",
        "wwwwwZZZwwwwww",
        "wwwwZZZZZwwwww",
        "wwwZZZZZZZwwww",
    ]

    static let ruiten: [String] = [
        "wwwwwwrwwwwwww",
        "wwwwwrrrwwwwww",
        "wwwwwrrrwwwwww",
        "wwwwrrrrrwwwww",
        "wwwrrrrrrrwwww",
        "wrrrrrrrrrrrww",
        "rrrrrrrrrrrrrw",
        "wrrrrrrrrrrrww",
        "wwwrrrrrrrwwww",
        "wwwwrrrrrwwwww",
        "wwwwwrrrwwwwww",
        "wwwwwrrrwwwwww",
        "wwwwwwrwwwwwww",
        "wwwwwwwwwwwwww",
    ]

    static let harten: [String] = [
        "wwRRRwwwRRRwww",
        "wRRRRRwRRRRRww",
        "RRRRRRwRRRRRRw",
        "RRRRRRRRRRRRRw",
        "wRRRRRRRRRRRww",
        "wRRRRRRRRRRRww",
        "wwRRRRRRRRRwww",
        "wwwRRRRRRRwwww",
        "wwwwRRRRRwwwww",
        "wwwwRRRRRwwwww",
        "wwwwwRRRwwwwww",
        "wwwwwRRRwwwwww",
        "wwwwwwRwwwwwww",
        "wwwwwwwwwwwwww",
    ]

    static func plaat(_ rang: Character) -> [String]? {
        switch rang {
        case "A": return aas
        case "H": return heer
        case "V": return vrouw
        case "B": return boer
        default: return nil
        }
    }

    static func palet(_ rang: Character) -> [(teken: Character, kleur: Int)]? {
        switch rang {
        case "A": return aasPalet
        case "H": return heerPalet
        case "V": return vrouwPalet
        case "B": return boerPalet
        default: return nil
        }
    }

    static func symbool(_ kleur: Int) -> [String] {
        switch kleur {
        case 0: return klaver
        case 1: return schoppen
        case 2: return ruiten
        default: return harten
        }
    }
}
