package nl.edsoft.klaverjas.kaarten

// Automatisch omgezet uit KaartData.swift (zelf gegenereerd uit Klaverjas/KJKRT.C
// door genkaarten.py) - niet met de hand aanpassen.
// Elk teken is een pixel; de kleurtabel per plaatkaart komt uit de switch in de
// bijbehorende C-functie. Kleur -1 betekent "GREEN + kleurnummer", waardoor die
// pixels per kaartkleur verschillen, precies als in het origineel.

internal object KaartData {

    val aas: List<String> = listOf(
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccccccccccccccccccccccccccccccc",
        "cccccccccccccccccccccaaaaaaacccccccccccccccccccccc",
        "cccccccccccccccccccccaaaaaaaaaaccccccccccccccccccc",
        "ccccccccccccccccccccaaaaaaaaaaaaaccccccccccccccccc",
        "cccccccccccccccccccaaaaaaaaaaacccccccccccccccccccc",
        "cccccccccccccccccccyyyyyyyyyyycccccccccccccccccccc",
        "cccccccaaaaacccccccyyyyyyyyyyccccaaaaaaccccccccccc",
        "ccccccaaaaaaaccccccccccccccccccaaaaaaaaaaaaacccccc",
        "ccccccaaaaaaaaccccccccccRccccccaaaaaaaaaaaaccccccc",
        "cccccyyyyyyyyyccccccccccRRcccccyyyyyyyyyaccccccccc",
        "ccccccyyyyyyyccccccccccRrRcccccyyyyyyyyccccccccccc",
        "ccccccyyyyyycccccccccccRrRcccccyyyyyyycccccccccccc",
        "cccccccccccccccccccccccRrrRccccccccccccccccccccccc",
        "ccccccccccccccccccccccRrrrRccccccccccccccccccccccc",
        "ccccccccccccccccccccccRrrrRccccccccccccccccccccccc",
        "ccccccRccccccccccccccRrrrrrRcccccccccccccccccccccc",
        "ccccccRRcRccccccccccRrruuurrRccccccccccccccccccccc",
        "cccccRrrzrRccccccccczYYyyyYYzccccccccccccccccccccc",
        "ccccRrrrzrRccccccccczyzuuuzuzccccccRcccccccccccccc",
        "cccczzzzzzzRRRRRcccczuuuuuuuzcccccRzRcccRccccccccc",
        "cccczeuuzuzrrrzRRRRRzeuzzzuuzccccRrzrRcRRccccccccc",
        "cccczeuuzezrrrrzrrrrzzzeuuzzzcccRrrzrRRrrRcccccccc",
        "cccczeuuzuzrrrrzrrrrzeeeuuuuzccRrrzzzRRrrrRccccccc",
        "cccczeeuzezrrrrrzrrrzeeeuuuuzcczzzuuzzzzzrRccccccc",
        "cccczeuuzuzrrrrrzrrrzeeeuuuuzcczeeuuzuzeezzccccccc",
        "cccczeuuzuzrrrrrrzrrzeeuuuuuzzczeeuuzuzuuuzccccccc",
        "cccczezzzzzzzzzzzzzzzeeuuuuuzuzzeeuuzuzuuuzccccccc",
        "cggczuzuzuzuzuzuzuzuzeuuuuuuzuuuzeuuzuzuuuzccccccc",
        "ggggzuzeuuuuuzzzzzzzzeuuuuuuzuuuzuuuzuzuuuzccccccc",
        "ggggzuzzzzzzzzuuuuuuzeuuuuuuzuuuzuuuzuzuuuzccccccc",
        "ggggzuzeeuguuguuuuuuzeuuuuuuzuuuzuuuzuzuuuziiiiiii",
        "gzgizuzeeuguuguuuuuuzuuuuuuuzuuuzuuuzuzuuuziiiiiii",
        "iziizuzeuugzggguuuuuzeeuuuuuzuuuzuuuzuzuuuzzzzzzzz",
        "iziizuzeuuuzuuuuuuuuzeuuuuuuzuuuzuuuzuzuubbuuuubbz",
        "iziizuzeguuzuuguuuugzeeuuuuuzuuuzUUUzbzUUbbuuuubbz",
        "iziizuzeguuzuggguuggzuuuuuuuzuuggbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbggggggggzuuuuuuuzggbbbbbbbbbbbbbbbbbbb",
        "wwwwwwwbbbbbbbbbbbbbzUUUUUUUzbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbwwwwwgbbbbbbbbbbbbwwwggbbbbbbbbbbbbbbb",
        "bbbbbbggwbbbbbbbbbbwwwwwwggbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbggbbbbbbbbbbbbbbbbbggbbbwwwwwwggbbbbbbbbbbbb",
        "bbbbbbbbbbbbbggbwwwwwwwbbbbbbbbbbbbbggbbbbbbbbbbbb",
        "bbbbbbbbbbbbbggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbgbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbgiiiiiiiiiiiiiiiibbbbbbbbbiiii",
        "bbbbiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    )

    val aasPalet: List<Pair<Char, Int>> = listOf(
        'a' to 7,
        'b' to 1,
        'c' to 9,
        'e' to 14,
        'g' to 2,
        'i' to 10,
        'j' to 12,
        'n' to 11,
        'o' to 3,
        'p' to 5,
        'r' to -1,
        't' to 13,
        'u' to 6,
        'w' to 15,
        'y' to 8,
        'z' to 0,
    )

    val heer: List<String> = listOf(
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEeJjEeJjEeJjxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEeJjEeJjEeJjxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEeJjEeJjEeJjxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxzzzzzzzzzzzzxxxxxxxxxxjxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEegeegeegeeExxxxxxxxxjjjjxxxxxxx",
        "xxxxxxxxxxxxxxxxxxEEEEEEEEEEEExxxxxxxxjjjjjjxxxxxx",
        "xxxxxxxxxxxxxxxxxxrrrwwwwwwwwwxxxxxxxxxjjjjxxxxxxx",
        "xxxxxxxxxxxxxxxxxxrrrwwwwwwwwwrxxxxxxxxxjjxxxxxxxx",
        "xxxxxxxxxxxxxxxxxrrrrrwzzwwzzrrxxxxxxxxEEEExxxxxxx",
        "xxxxxxxxxxxxxxxxrrrrrwwwwzwwwrrxxxxxxxEeeExxxxxxxx",
        "xxxxxxxxxxxxxxxxrrrrwwwwwwzwwrrxxxxxxxEbeExxxxxxxx",
        "xxxxxxxxxxxxxxxrrrrrwwwwwwzwwrrxxxxxxEeeExxxxxxxxx",
        "xxxxxxxxxxxxxxxrrrrrwwwwwzzwwrrxxxxxxEjjExxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrwwwwwwwwwrrxxxxxEjjExxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrzrrrzrrrxxxxxEeeExxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrrrzzrrrrxxxxxEeeExxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrrrrrrrwrxxxxEegExxxxxxxxxxx",
        "xxxxxxxxxxxxxxrrrrrrrrrrrrrrrwrxxxxEeeExxxxxxxxxxx",
        "xxxxxxxxxxxxxxrErrPrrrrrrrrrrPrxxxxEbeExxxxxxxxxxx",
        "xxxxxxxxxxxxxxEeePppppprrrrrrpppPxEeeExxxxxxxxxxxx",
        "xxxxxxxxxxxxxEeeePppppppprrrpppPeEppExxxxxxxxxxxxx",
        "xxxxxxxxxxxBbEeeeePpppppppppppPeeEppExxxxxxxxxxxxx",
        "xxxxxxxxxxBbbbbEeeeePPPPppppEEeeEeeExxxxxxxxxxxxxx",
        "xxxxxxxxxBbbbbbEEeeeeeeeEEEEeeeeEeeExxxxxxxxxxxxxx",
        "xxxxxxxxBbbbbbbbbEeeeeeeeeeeeeeeEeeExxxxxxxxxxxxxx",
        "xxxxxxxxBbbbbbbbbbEEeeeeeeeeeeeEeeEBxxxxxxxxxxxxxx",
        "xxxxxxxxBbbbbbbbbbbbbEEEEEEEEbEeeEbbBxxxxxxxxxxxxx",
        "xxxxxxxBbbbbbbbbbbbbbbbbbbbbbbEeeEbbbbBxxxxxxxxxxx",
        "xxxxxxxBbbbbbbbbbbbbbbbbGbbbbbErrEbbbbbBxxxxxxxxxx",
        "xxxxxxxBbbbbbbbbbbbbbbbGgGGbbErrEbbbbbbBxxxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbbbGggggGbEeeEbbbbbbbBxxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbbbGgggggEttEbbbbbbbbBxxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbbGgpppggEetEbbbbbbbbbBxxxxxxxx",
        "xxxxxxBbbbbbbbbbbbbbGzzpppzEeeEbbbbbbbbbbBxxxxxxxx",
        "xxxxxBbbbbbbbbbbbbbbGggpppgEeeEgBbbbbbbbbbBxxxxxxx",
        "xxxxxBbbbbbbbbbbbbbGgggggggEezEgBbbbbbbbbbBxxxxxxx",
        "xxxxxBbbbbbbbbbbbbbGggggggEieEgggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbbbGggggggEiiEgggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbbGggggggEeeEggggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbbGggggggEooEggggBbbbbbbbbbBxxxxxx",
        "xxxxxBbbbbbbbbbbbGgggggggEooEgggggBbbbbbbbbbBxxxxx",
        "xxxxxBbbbbbbbbbbbGggggggEeeEggggggBbbbbbbbbbBxxxxx",
        "xxxxxBbbbbbbbbbbGgtttgggEeeEggggttBbbbbbbbbbBxxxxx",
        "xxxxBbbbbbbbbbbGgttgttgEeuEggggttgtBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbbGgttgggttEuuEgggttgggBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbbGttgggggEeeEgggttggggBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbGttggggggEeeEggttgggggBbbbbbbbbbBxxxx",
        "xxxxBbbbbbbbbGtgggggggEeetgttggggggBbbbbbbbbbBxxxx",
    )

    val heerPalet: List<Pair<Char, Int>> = listOf(
        'a' to 7,
        'b' to 1,
        'c' to 9,
        'e' to 14,
        'g' to 2,
        'i' to 10,
        'j' to 12,
        'o' to 3,
        'p' to 5,
        'r' to -1,
        't' to 11,
        'u' to 6,
        'w' to 15,
        'x' to 13,
        'y' to 8,
        'z' to 0,
    )

    val vrouw: List<String> = listOf(
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaiijjiijjiijaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaiijjiijjiijaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaEEEEEEEEEEEaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaEeeettteeeEaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaEeettttteeEaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaazzzzzzzzzzzaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaRrrrrrrrrrrrRaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrzrrrrrrrrrrRaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrzrrrrrrrrrrrRaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrzwwwwwwwwrrrPPPaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaRrrwwwwwwwwwrrrPppPaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaRrwwwwwzzwwwrPppppPaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaZwzzwwzzwwwrrPppPcaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaZwzzwzwwwwwwrPPPccaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaZwwwzwwwwwwwZcccccaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaZwwwzzwwwwwwZcccccaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaZwwwwwzwwwZccccccaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaZwzzzwwwzZcccccccaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwzwZcccccccaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZzzzzwwwwZcccccccaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwwwwZcccccccaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwwwwwZccccccaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaZwwwwwwwwwZcccccccaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaBZZZwwwwwwwwwwZccccccaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaBbBwwwwwwwwwwwBbBccccccaaaaaaaaaa",
        "aaaaaaaaaaaIZZZZZZBbbbBwwwwwwBbbbbEEccccaaaaaaaaaa",
        "aaaaaaaaaIiiiIaWWWwwBbbBBBBBBbbbbEeeeEccaaaaaaaaaa",
        "aaaaaaaaIIiiIwwwwwwwBbbbbbbbbbbbEeeeeeEcaaaaaaaaaa",
        "aaaaaaaaIiiiiIwwwwwwwwwBBBBBwwwEeeeeeeEaaaaaaaaaaa",
        "aaaaaaaaIiiiiiIwwwwwwwwwwwwwwwEEeeeeeeeEaaaaaaaaaa",
        "aaaaaaaIiiiiiiIwwwwwwzwwwwwwwwEeeeeeeeeEEaaaaaaaaa",
        "aaaaaaaIiiiiiiiIwwwwzwwwwwwwIEeeeeeeeeeeEaaaaaaaaa",
        "aaaaaaIiiiiiiiiIwwwzwwwwwwIiEeeeeeeeeeeeIaaaaaaaaa",
        "aaaaaaIiiiiiiiiiIwwzwwwwIiiEeeeeeeeeeeIiIaaaaaaaaa",
        "aaaaaaIiiiiiiiiiIwzwwwIiiiiEeeeeeeeeIiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiIzwIiiiiiiEeeeeeeeIiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiIIiiiiiiEeeeeeeeIiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiiieeeeeeeeIiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiiEeeeeeeeeIiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiIaaaaaaaaa",
        "aaaaaIiiiiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiIaaaaaaaaa",
        "aaaaUuiiiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiiUaaaaaaaaa",
        "aaaaUuuiiiiiiiiiiiiiiiEeeeeeeeEiiiiiiiUuUaaaaaaaaa",
        "aaaaUuuuiiiiiiiiiiiiiEeeeeeeeEiiiijjjUuuUaaaaaaaaa",
        "aaaaUuuujjjjjjjiiiiiiEeeeeeeeEjjjjjjjUuuUaaaaaaaaa",
        "aaaaUuuujjjjjjjjjjjjEeeeeeeeEjjjjjjjUuuuUaaaaaaaaa",
        "aaaaUuuujjjjjjjjjjjjEeeeeeeeEjjjjjiUuuuuUaaaaaaaaa",
        "aaaUuuuuiiiiijjjjjjEeeeeeeeEiiiiiiUuuuuuUaaaaaaaaa",
    )

    val vrouwPalet: List<Pair<Char, Int>> = listOf(
        'a' to 7,
        'b' to 1,
        'c' to 9,
        'e' to 14,
        'g' to 2,
        'i' to 10,
        'j' to 12,
        'o' to 3,
        'p' to 5,
        'r' to -1,
        't' to 11,
        'u' to 6,
        'w' to 15,
        'x' to 13,
        'y' to 8,
        'z' to 0,
    )

    val boer: List<String> = listOf(
        "ccccccccccccccccccccccccccccJJJJJccccccccccccccccc",
        "ccccccccccccccccccccccccccJJjjjjJccccccccccccccccc",
        "cccccccccccccccccccccccccJjjjjjJcccccccccccccccccc",
        "ccccccccccccccccccccccccJjjjjjJccccccccccccccccccc",
        "cccccccccccccccccccccccJjjjjjJcccccccccccccccccccc",
        "cccccwwwwwwwwwwwwwccccJjjjjJJccccccccccccccccccccc",
        "ccccwwwwwwwwwwwwwwwwpJjjjJJcccccccccwwwwwccccccccc",
        "ccccccwwwwwwwwwwwwpPJjjJJPPccccccccwwwwwwwcccccccc",
        "ccccwwwwwwwwwwwwwwwPJjJppppPPccccccccccccccccccccc",
        "ccwwwwwwwwwwwwwwcccPJJpppppppPPPcccccccccccccccccc",
        "cwwwwwwwwwwwwwcccPPpppppppppppppPPPcccccgggggggccc",
        "cwwwwwwwwwwwwwcccPppppppppppppppppPccgggggggjjgggc",
        "cyyyyyyyyyyyyyccccPPPPPPPPPPpppppPPccgggjjggjjggjj",
        "cyyyyyyyyyyyyycccccRrrrWwwwPPPPPPcccggggjjggggggjj",
        "cccccccYcccccccccccRrrWwwwwwwwrrRcccggggggjjggjjgg",
        "cccccccYYcccccccccRrrWwZZwwZZwWrRccggjjgggjjggjjgg",
        "cccccccYyYccccccccRrWwwwwZwwwwWrRcccgjjggjjggggggg",
        "cccccccYyyYYccccccRrWwwwwZwwwwWrRcccgggggjjggggjjg",
        "cccccccYyyYyYcccccRrWwwwwZwwwwWrRcccccgggggjjggjjg",
        "ccccccccYyYYyYccccRrrWwWrrrrwwWrRcccccccgggjjggggg",
        "ccccccccYyYUYyYcccRrrrWWrrrrwwWrRccccccccccuuuuccc",
        "ccccccccYyYUUYyYccRRRRwwZZZZWWRRRccccccccccuuuuccc",
        "ccccccccYyYUuUYyYccccccZrrrrwzwRcccccccccccuuuuccc",
        "ccccccccYyYcUuUYYYccccZWrrrrzwwZcccccccccccuuuuccc",
        "cccccccccYYcUuUccYYcccZwrrrrwwwwZccccccccccuuuuccc",
        "cccccccccYcccUuUcccYcZWwwwwwwwwwZccccccccccuuuuccc",
        "cccccccccYcccUuUcccccZWWWWWWWWWWWZEEEccccccuuuuccc",
        "ccccccccccccccUuUccjjjjwwwjeeeeeeeeeeEcccccuuuuccc",
        "cccccccccccccccUuUjjjjjjjjEeeeeeeeeeeeEccccuuuuccc",
        "ccccccccccGGGGGUuUbbbjjjjEeeeeeeeeeeeeeEcccuuuuccc",
        "ccccccccGGggggggUuUbbbbbbEeeeeeeeeeeeeeEcccuuuuccc",
        "cccccccGgggggggugUuUbbbbEeeeeeeeeeeeeeeEEccuuuuccc",
        "cccccccGgggggggggUuUbbbEeeeeeeeeeeeeEEEggGcuuuuccc",
        "ccccccGggggggggBbBUuUbEeeeeeeeeeeeeEgggggGcuuuuccc",
        "ccccccGgggggggBbbbUuUeEeeeeeeeeeeEgggggggGcuuuuccc",
        "cccccGgggggggBbbbbbUuUeeeeeeeeeeEgggggggggGuuuuccc",
        "cccccGgggggggBbbbbgUuUeeeeeeeeeEggggggggggGuuuuccc",
        "cccccGgggggggBbbbbbbUuUeeeeeeeeEgggggggggggGuuuccc",
        "cccccGgggggggBbbbbbbUuUeeeeeeeEbbbGgggggggggGuuccc",
        "iiiiiGgggggggBbbbbbEeUuUeeeeeEbbbbBGgggggggggGuiii",
        "iiiiiGgggggggBbbbbEeeUuUeeeeeEbbbbBGggggggggggGiii",
        "iiiiiGgggggggBbbbEeeeeUuUeeeeEbbbbBiGgggggggggGiii",
        "iiiiGgggggggBbbbbEeeeeUuUeeeEbbbbbBiiGggggggggGiii",
        "iiiiGgggggggBbbbEeeeeeeUuUeeEbbbbBiiiGgggggggGiiii",
        "iiiiGgggggggBbbbEeeeeeeUuUeebbbbbBiiGggggggggGiiii",
        "iiiiGgggggggBbbEeeeeeeeeUuUeebbbbBiiGgggggggGiiiii",
        "iiiiGgggggggBbbEeeeeeeeeeUuUebbbbBiiGggggggGiiiiii",
        "iiiiGgggggggBbbEeeeeeeeeEUuUebbbbBiGggggggGiiiiiii",
        "iiiiGgggggggBBeeeeeeeeeeEbUuUbbbbBGgggggggGiiiiiii",
    )

    val boerPalet: List<Pair<Char, Int>> = listOf(
        'a' to 7,
        'b' to 1,
        'c' to 9,
        'e' to 14,
        'g' to 2,
        'i' to 10,
        'j' to 12,
        'o' to 3,
        'p' to 5,
        'r' to -1,
        't' to 11,
        'u' to 6,
        'w' to 15,
        'x' to 13,
        'y' to 8,
        'z' to 0,
    )

    val klaver: List<String> = listOf(
        "wwwwwzzzwwwwww",
        "wwwwzzzzzwwwww",
        "wwwwzzzzzwwwww",
        "wwwwwzzzwwwwww",
        "wzzwwwzwwwzzww",
        "zzzzzwzwzzzzzw",
        "zzzzzzzzzzzzzw",
        "zzzzzwzwzzzzzw",
        "wzzwwwzwwwzzww",
        "wwwwwwzwwwwwww",
        "wwwwwzzzwwwwww",
        "wwwwwzzzwwwwww",
        "wwwwzzzzzwwwww",
        "wwwwwwwwwwwwww",
    )

    val schoppen: List<String> = listOf(
        "wwwwwwZwwwwwww",
        "wwwwwZZZwwwwww",
        "wwwwZZZZZwwwww",
        "wwZZZZZZZZZwww",
        "wZZZZZZZZZZZww",
        "ZZZZZZZZZZZZZw",
        "ZZZZZZZZZZZZZw",
        "ZZZZZZZZZZZZZw",
        "wZZZZwZwZZZZww",
        "wwZZwZZZwZZwww",
        "wwwwwwZwwwwwww",
        "wwwwwZZZwwwwww",
        "wwwwZZZZZwwwww",
        "wwwZZZZZZZwwww",
    )

    val ruiten: List<String> = listOf(
        "wwwwwwrwwwwwww",
        "wwwwwrrrwwwwww",
        "wwwwwrrrwwwwww",
        "wwwwrrrrrwwwww",
        "wwwrrrrrrrwwww",
        "wrrrrrrrrrrrww",
        "rrrrrrrrrrrrrw",
        "wrrrrrrrrrrrww",
        "wwwrrrrrrrwwww",
        "wwwwrrrrrwwwww",
        "wwwwwrrrwwwwww",
        "wwwwwrrrwwwwww",
        "wwwwwwrwwwwwww",
        "wwwwwwwwwwwwww",
    )

    val harten: List<String> = listOf(
        "wwRRRwwwRRRwww",
        "wRRRRRwRRRRRww",
        "RRRRRRwRRRRRRw",
        "RRRRRRRRRRRRRw",
        "wRRRRRRRRRRRww",
        "wRRRRRRRRRRRww",
        "wwRRRRRRRRRwww",
        "wwwRRRRRRRwwww",
        "wwwwRRRRRwwwww",
        "wwwwRRRRRwwwww",
        "wwwwwRRRwwwwww",
        "wwwwwRRRwwwwww",
        "wwwwwwRwwwwwww",
        "wwwwwwwwwwwwww",
    )

    fun plaat(rang: Char): List<String>? = when (rang) {
        'A' -> aas
        'H' -> heer
        'V' -> vrouw
        'B' -> boer
        else -> null
    }

    fun palet(rang: Char): List<Pair<Char, Int>>? = when (rang) {
        'A' -> aasPalet
        'H' -> heerPalet
        'V' -> vrouwPalet
        'B' -> boerPalet
        else -> null
    }

    fun symbool(kleur: Int): List<String> = when (kleur) {
        0 -> klaver
        1 -> schoppen
        2 -> ruiten
        else -> harten
    }
}
